### ISSUE TITLE
clear system auth tokens 

### ISSUE THREAD

**Issue by srobi** [panthernet/ThunderED#57]
I had difficulties with auth after one of the feeder changed corporate. e.g. the feeder discord auth with one corporate before then joined a new corp and auth for discord and  feeder  too. The ESI log  started recording: 
[   Error]: [ContractNotif] Request failure: https://esi.evetech.net/latest/corporations/XXXXXXXX/contracts/?datasource=tranquility&language=en-us
{"error":"Character is not in the corporation"}

I could circumvent the issue by setting up a different feeder who is not auth on discord. As this is a relatively infrequent event I would suggest to implement a system command (via discord) that remove all system auth related info/token from DB but keep the discord/non-discord auths in place.  It should be restricted to use by role above bot's role ... or some other permission system (web). I run the bot as service so console command would not be handy.

**Comment by panthernet** [comment]
The problem is probably related to cache where's user corporation is stored. I don't want to make user data cache-less as it is called quite frequently but probably can make it so the first query upon module startup will always fetch new data from ESI.

This will allow data to be refresh upon bot restart or !rehash command.

**Comment by panthernet** [comment]
Implemented in v1.3.8
